POST localhost:8080/api/protected/me/change-password
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzE2MDkwNzksInN1YiI6MTgzfQ.hRrWVnoAtIJc60eZ1M6Az4y7aas3mXkF_9P3b38rg-E
content-type: application/json

{
  "old_password": "arS12**12",
  "new_password": "testPass12",
  "confirm_password": "testPass12"
}