POST localhost:8080/api/register
content-type: application/json

{
  "name": "arshia",
  "last_name": "rezagholi",
  "username": "arshio",
  "password": "Arshio12123123123",
  "email": "arshiarezagholi1212@gmail.com"
}
