services:
  main:
    build:
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

  postgres:
    image: "postgres:latest"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5432:5432"
    env_file:
      - .env