services:
  main:
    build:
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: "postgres:latest"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5433:5432"
    env_file:
      - .env