// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"docuSync/ent/document"
	"docuSync/ent/predicate"
	"docuSync/ent/user"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDocument = "Document"
	TypeUser     = "User"
)

// DocumentMutation represents an operation that mutates the Document nodes in the graph.
type DocumentMutation struct {
	config
	op                   Op
	typ                  string
	id                   *int
	clearedFields        map[string]struct{}
	editors              map[int]struct{}
	removededitors       map[int]struct{}
	clearededitors       bool
	owner                *int
	clearedowner         bool
	allowed_users        map[int]struct{}
	removedallowed_users map[int]struct{}
	clearedallowed_users bool
	done                 bool
	oldValue             func(context.Context) (*Document, error)
	predicates           []predicate.Document
}

var _ ent.Mutation = (*DocumentMutation)(nil)

// documentOption allows management of the mutation configuration using functional options.
type documentOption func(*DocumentMutation)

// newDocumentMutation creates new mutation for the Document entity.
func newDocumentMutation(c config, op Op, opts ...documentOption) *DocumentMutation {
	m := &DocumentMutation{
		config:        c,
		op:            op,
		typ:           TypeDocument,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDocumentID sets the ID field of the mutation.
func withDocumentID(id int) documentOption {
	return func(m *DocumentMutation) {
		var (
			err   error
			once  sync.Once
			value *Document
		)
		m.oldValue = func(ctx context.Context) (*Document, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Document.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDocument sets the old Document of the mutation.
func withDocument(node *Document) documentOption {
	return func(m *DocumentMutation) {
		m.oldValue = func(context.Context) (*Document, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DocumentMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DocumentMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DocumentMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DocumentMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Document.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// AddEditorIDs adds the "editors" edge to the User entity by ids.
func (m *DocumentMutation) AddEditorIDs(ids ...int) {
	if m.editors == nil {
		m.editors = make(map[int]struct{})
	}
	for i := range ids {
		m.editors[ids[i]] = struct{}{}
	}
}

// ClearEditors clears the "editors" edge to the User entity.
func (m *DocumentMutation) ClearEditors() {
	m.clearededitors = true
}

// EditorsCleared reports if the "editors" edge to the User entity was cleared.
func (m *DocumentMutation) EditorsCleared() bool {
	return m.clearededitors
}

// RemoveEditorIDs removes the "editors" edge to the User entity by IDs.
func (m *DocumentMutation) RemoveEditorIDs(ids ...int) {
	if m.removededitors == nil {
		m.removededitors = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.editors, ids[i])
		m.removededitors[ids[i]] = struct{}{}
	}
}

// RemovedEditors returns the removed IDs of the "editors" edge to the User entity.
func (m *DocumentMutation) RemovedEditorsIDs() (ids []int) {
	for id := range m.removededitors {
		ids = append(ids, id)
	}
	return
}

// EditorsIDs returns the "editors" edge IDs in the mutation.
func (m *DocumentMutation) EditorsIDs() (ids []int) {
	for id := range m.editors {
		ids = append(ids, id)
	}
	return
}

// ResetEditors resets all changes to the "editors" edge.
func (m *DocumentMutation) ResetEditors() {
	m.editors = nil
	m.clearededitors = false
	m.removededitors = nil
}

// SetOwnerID sets the "owner" edge to the User entity by id.
func (m *DocumentMutation) SetOwnerID(id int) {
	m.owner = &id
}

// ClearOwner clears the "owner" edge to the User entity.
func (m *DocumentMutation) ClearOwner() {
	m.clearedowner = true
}

// OwnerCleared reports if the "owner" edge to the User entity was cleared.
func (m *DocumentMutation) OwnerCleared() bool {
	return m.clearedowner
}

// OwnerID returns the "owner" edge ID in the mutation.
func (m *DocumentMutation) OwnerID() (id int, exists bool) {
	if m.owner != nil {
		return *m.owner, true
	}
	return
}

// OwnerIDs returns the "owner" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// OwnerID instead. It exists only for internal usage by the builders.
func (m *DocumentMutation) OwnerIDs() (ids []int) {
	if id := m.owner; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetOwner resets all changes to the "owner" edge.
func (m *DocumentMutation) ResetOwner() {
	m.owner = nil
	m.clearedowner = false
}

// AddAllowedUserIDs adds the "allowed_users" edge to the User entity by ids.
func (m *DocumentMutation) AddAllowedUserIDs(ids ...int) {
	if m.allowed_users == nil {
		m.allowed_users = make(map[int]struct{})
	}
	for i := range ids {
		m.allowed_users[ids[i]] = struct{}{}
	}
}

// ClearAllowedUsers clears the "allowed_users" edge to the User entity.
func (m *DocumentMutation) ClearAllowedUsers() {
	m.clearedallowed_users = true
}

// AllowedUsersCleared reports if the "allowed_users" edge to the User entity was cleared.
func (m *DocumentMutation) AllowedUsersCleared() bool {
	return m.clearedallowed_users
}

// RemoveAllowedUserIDs removes the "allowed_users" edge to the User entity by IDs.
func (m *DocumentMutation) RemoveAllowedUserIDs(ids ...int) {
	if m.removedallowed_users == nil {
		m.removedallowed_users = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.allowed_users, ids[i])
		m.removedallowed_users[ids[i]] = struct{}{}
	}
}

// RemovedAllowedUsers returns the removed IDs of the "allowed_users" edge to the User entity.
func (m *DocumentMutation) RemovedAllowedUsersIDs() (ids []int) {
	for id := range m.removedallowed_users {
		ids = append(ids, id)
	}
	return
}

// AllowedUsersIDs returns the "allowed_users" edge IDs in the mutation.
func (m *DocumentMutation) AllowedUsersIDs() (ids []int) {
	for id := range m.allowed_users {
		ids = append(ids, id)
	}
	return
}

// ResetAllowedUsers resets all changes to the "allowed_users" edge.
func (m *DocumentMutation) ResetAllowedUsers() {
	m.allowed_users = nil
	m.clearedallowed_users = false
	m.removedallowed_users = nil
}

// Where appends a list predicates to the DocumentMutation builder.
func (m *DocumentMutation) Where(ps ...predicate.Document) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DocumentMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DocumentMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Document, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DocumentMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DocumentMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Document).
func (m *DocumentMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DocumentMutation) Fields() []string {
	fields := make([]string, 0, 0)
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DocumentMutation) Field(name string) (ent.Value, bool) {
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DocumentMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown Document field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DocumentMutation) SetField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Document field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DocumentMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DocumentMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DocumentMutation) AddField(name string, value ent.Value) error {
	return fmt.Errorf("unknown Document numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DocumentMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DocumentMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DocumentMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Document nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DocumentMutation) ResetField(name string) error {
	return fmt.Errorf("unknown Document field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DocumentMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.editors != nil {
		edges = append(edges, document.EdgeEditors)
	}
	if m.owner != nil {
		edges = append(edges, document.EdgeOwner)
	}
	if m.allowed_users != nil {
		edges = append(edges, document.EdgeAllowedUsers)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DocumentMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case document.EdgeEditors:
		ids := make([]ent.Value, 0, len(m.editors))
		for id := range m.editors {
			ids = append(ids, id)
		}
		return ids
	case document.EdgeOwner:
		if id := m.owner; id != nil {
			return []ent.Value{*id}
		}
	case document.EdgeAllowedUsers:
		ids := make([]ent.Value, 0, len(m.allowed_users))
		for id := range m.allowed_users {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DocumentMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removededitors != nil {
		edges = append(edges, document.EdgeEditors)
	}
	if m.removedallowed_users != nil {
		edges = append(edges, document.EdgeAllowedUsers)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DocumentMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case document.EdgeEditors:
		ids := make([]ent.Value, 0, len(m.removededitors))
		for id := range m.removededitors {
			ids = append(ids, id)
		}
		return ids
	case document.EdgeAllowedUsers:
		ids := make([]ent.Value, 0, len(m.removedallowed_users))
		for id := range m.removedallowed_users {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DocumentMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearededitors {
		edges = append(edges, document.EdgeEditors)
	}
	if m.clearedowner {
		edges = append(edges, document.EdgeOwner)
	}
	if m.clearedallowed_users {
		edges = append(edges, document.EdgeAllowedUsers)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DocumentMutation) EdgeCleared(name string) bool {
	switch name {
	case document.EdgeEditors:
		return m.clearededitors
	case document.EdgeOwner:
		return m.clearedowner
	case document.EdgeAllowedUsers:
		return m.clearedallowed_users
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DocumentMutation) ClearEdge(name string) error {
	switch name {
	case document.EdgeOwner:
		m.ClearOwner()
		return nil
	}
	return fmt.Errorf("unknown Document unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DocumentMutation) ResetEdge(name string) error {
	switch name {
	case document.EdgeEditors:
		m.ResetEditors()
		return nil
	case document.EdgeOwner:
		m.ResetOwner()
		return nil
	case document.EdgeAllowedUsers:
		m.ResetAllowedUsers()
		return nil
	}
	return fmt.Errorf("unknown Document edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op                       Op
	typ                      string
	id                       *int
	clearedFields            map[string]struct{}
	allowed_documents        map[int]struct{}
	removedallowed_documents map[int]struct{}
	clearedallowed_documents bool
	owned_documents          map[int]struct{}
	removedowned_documents   map[int]struct{}
	clearedowned_documents   bool
	edited_documents         map[int]struct{}
	removededited_documents  map[int]struct{}
	clearededited_documents  bool
	done                     bool
	oldValue                 func(context.Context) (*User, error)
	predicates               []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// AddAllowedDocumentIDs adds the "allowed_documents" edge to the Document entity by ids.
func (m *UserMutation) AddAllowedDocumentIDs(ids ...int) {
	if m.allowed_documents == nil {
		m.allowed_documents = make(map[int]struct{})
	}
	for i := range ids {
		m.allowed_documents[ids[i]] = struct{}{}
	}
}

// ClearAllowedDocuments clears the "allowed_documents" edge to the Document entity.
func (m *UserMutation) ClearAllowedDocuments() {
	m.clearedallowed_documents = true
}

// AllowedDocumentsCleared reports if the "allowed_documents" edge to the Document entity was cleared.
func (m *UserMutation) AllowedDocumentsCleared() bool {
	return m.clearedallowed_documents
}

// RemoveAllowedDocumentIDs removes the "allowed_documents" edge to the Document entity by IDs.
func (m *UserMutation) RemoveAllowedDocumentIDs(ids ...int) {
	if m.removedallowed_documents == nil {
		m.removedallowed_documents = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.allowed_documents, ids[i])
		m.removedallowed_documents[ids[i]] = struct{}{}
	}
}

// RemovedAllowedDocuments returns the removed IDs of the "allowed_documents" edge to the Document entity.
func (m *UserMutation) RemovedAllowedDocumentsIDs() (ids []int) {
	for id := range m.removedallowed_documents {
		ids = append(ids, id)
	}
	return
}

// AllowedDocumentsIDs returns the "allowed_documents" edge IDs in the mutation.
func (m *UserMutation) AllowedDocumentsIDs() (ids []int) {
	for id := range m.allowed_documents {
		ids = append(ids, id)
	}
	return
}

// ResetAllowedDocuments resets all changes to the "allowed_documents" edge.
func (m *UserMutation) ResetAllowedDocuments() {
	m.allowed_documents = nil
	m.clearedallowed_documents = false
	m.removedallowed_documents = nil
}

// AddOwnedDocumentIDs adds the "owned_documents" edge to the Document entity by ids.
func (m *UserMutation) AddOwnedDocumentIDs(ids ...int) {
	if m.owned_documents == nil {
		m.owned_documents = make(map[int]struct{})
	}
	for i := range ids {
		m.owned_documents[ids[i]] = struct{}{}
	}
}

// ClearOwnedDocuments clears the "owned_documents" edge to the Document entity.
func (m *UserMutation) ClearOwnedDocuments() {
	m.clearedowned_documents = true
}

// OwnedDocumentsCleared reports if the "owned_documents" edge to the Document entity was cleared.
func (m *UserMutation) OwnedDocumentsCleared() bool {
	return m.clearedowned_documents
}

// RemoveOwnedDocumentIDs removes the "owned_documents" edge to the Document entity by IDs.
func (m *UserMutation) RemoveOwnedDocumentIDs(ids ...int) {
	if m.removedowned_documents == nil {
		m.removedowned_documents = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.owned_documents, ids[i])
		m.removedowned_documents[ids[i]] = struct{}{}
	}
}

// RemovedOwnedDocuments returns the removed IDs of the "owned_documents" edge to the Document entity.
func (m *UserMutation) RemovedOwnedDocumentsIDs() (ids []int) {
	for id := range m.removedowned_documents {
		ids = append(ids, id)
	}
	return
}

// OwnedDocumentsIDs returns the "owned_documents" edge IDs in the mutation.
func (m *UserMutation) OwnedDocumentsIDs() (ids []int) {
	for id := range m.owned_documents {
		ids = append(ids, id)
	}
	return
}

// ResetOwnedDocuments resets all changes to the "owned_documents" edge.
func (m *UserMutation) ResetOwnedDocuments() {
	m.owned_documents = nil
	m.clearedowned_documents = false
	m.removedowned_documents = nil
}

// AddEditedDocumentIDs adds the "edited_documents" edge to the Document entity by ids.
func (m *UserMutation) AddEditedDocumentIDs(ids ...int) {
	if m.edited_documents == nil {
		m.edited_documents = make(map[int]struct{})
	}
	for i := range ids {
		m.edited_documents[ids[i]] = struct{}{}
	}
}

// ClearEditedDocuments clears the "edited_documents" edge to the Document entity.
func (m *UserMutation) ClearEditedDocuments() {
	m.clearededited_documents = true
}

// EditedDocumentsCleared reports if the "edited_documents" edge to the Document entity was cleared.
func (m *UserMutation) EditedDocumentsCleared() bool {
	return m.clearededited_documents
}

// RemoveEditedDocumentIDs removes the "edited_documents" edge to the Document entity by IDs.
func (m *UserMutation) RemoveEditedDocumentIDs(ids ...int) {
	if m.removededited_documents == nil {
		m.removededited_documents = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.edited_documents, ids[i])
		m.removededited_documents[ids[i]] = struct{}{}
	}
}

// RemovedEditedDocuments returns the removed IDs of the "edited_documents" edge to the Document entity.
func (m *UserMutation) RemovedEditedDocumentsIDs() (ids []int) {
	for id := range m.removededited_documents {
		ids = append(ids, id)
	}
	return
}

// EditedDocumentsIDs returns the "edited_documents" edge IDs in the mutation.
func (m *UserMutation) EditedDocumentsIDs() (ids []int) {
	for id := range m.edited_documents {
		ids = append(ids, id)
	}
	return
}

// ResetEditedDocuments resets all changes to the "edited_documents" edge.
func (m *UserMutation) ResetEditedDocuments() {
	m.edited_documents = nil
	m.clearededited_documents = false
	m.removededited_documents = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 0)
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.allowed_documents != nil {
		edges = append(edges, user.EdgeAllowedDocuments)
	}
	if m.owned_documents != nil {
		edges = append(edges, user.EdgeOwnedDocuments)
	}
	if m.edited_documents != nil {
		edges = append(edges, user.EdgeEditedDocuments)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeAllowedDocuments:
		ids := make([]ent.Value, 0, len(m.allowed_documents))
		for id := range m.allowed_documents {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeOwnedDocuments:
		ids := make([]ent.Value, 0, len(m.owned_documents))
		for id := range m.owned_documents {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeEditedDocuments:
		ids := make([]ent.Value, 0, len(m.edited_documents))
		for id := range m.edited_documents {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedallowed_documents != nil {
		edges = append(edges, user.EdgeAllowedDocuments)
	}
	if m.removedowned_documents != nil {
		edges = append(edges, user.EdgeOwnedDocuments)
	}
	if m.removededited_documents != nil {
		edges = append(edges, user.EdgeEditedDocuments)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeAllowedDocuments:
		ids := make([]ent.Value, 0, len(m.removedallowed_documents))
		for id := range m.removedallowed_documents {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeOwnedDocuments:
		ids := make([]ent.Value, 0, len(m.removedowned_documents))
		for id := range m.removedowned_documents {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeEditedDocuments:
		ids := make([]ent.Value, 0, len(m.removededited_documents))
		for id := range m.removededited_documents {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedallowed_documents {
		edges = append(edges, user.EdgeAllowedDocuments)
	}
	if m.clearedowned_documents {
		edges = append(edges, user.EdgeOwnedDocuments)
	}
	if m.clearededited_documents {
		edges = append(edges, user.EdgeEditedDocuments)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeAllowedDocuments:
		return m.clearedallowed_documents
	case user.EdgeOwnedDocuments:
		return m.clearedowned_documents
	case user.EdgeEditedDocuments:
		return m.clearededited_documents
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeAllowedDocuments:
		m.ResetAllowedDocuments()
		return nil
	case user.EdgeOwnedDocuments:
		m.ResetOwnedDocuments()
		return nil
	case user.EdgeEditedDocuments:
		m.ResetEditedDocuments()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
